// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"echo_postgre/controller"
	"echo_postgre/repository/implement"
	"echo_postgre/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserController(db *gorm.DB) controller.UserController {
	iUserRepository := implement.NewUserImplement(db)
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController
}

func InitializeSettingsController(db *gorm.DB) controller.SettingsController {
	iSettingsRepository := implement.NewSettingsImplement(db)
	iSettingsService := service.NewSettingsService(iSettingsRepository)
	settingsController := controller.NewSettingsController(iSettingsService)
	return settingsController
}

func InitializeAuthController(db *gorm.DB) controller.AuthController {
	iUserRepository := implement.NewUserImplement(db)
	iSettingsRepository := implement.NewSettingsImplement(db)
	iAuthService := service.NewAuthService(iUserRepository, iSettingsRepository)
	authController := controller.NewAuthController(iAuthService)
	return authController
}
